### ISSUE TITLE
Typing Return does not scroll

### ISSUE THREAD

**Issue by winkler1** [prakhar1989/react-term#1]
Cool project - love your use of styles and the minimalism here.

Slight bug: tying return on a new line stays scrolled out of view--
![image](https://cloud.githubusercontent.com/assets/883896/7670603/bbcc6f02-fc78-11e4-9eba-756b598ff083.png)

Typing a real char does the scrolling-
![image](https://cloud.githubusercontent.com/assets/883896/7670607/d2053042-fc78-11e4-81fa-3db7b9b3b446.png)

**Comment by prakhar1989** [comment]
Ah! Yes, I was aware of that. Any ideas on how to fix it?  Thank you for liking my project though. :grinning:

**Comment by ErezSha** [comment]
You should update the element's scrollTop to it's scrollHeight after it's updated.
This works for me on my component:
componentDidUpdate () {
    let el = React.findDOMNode(this)
    el.scrollTop = el.scrollHeight
  }

**Comment by prakhar1989** [comment]
@ErezSha: Just released a fix. Had to slightly change the code you had suggested. But it works now. Much thanks :beers:
